/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuizIdWaitingImport } from './routes/$quizId/waiting'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const QuizIdPlayLazyImport = createFileRoute('/$quizId/play')()
const AdminCreateIndexLazyImport = createFileRoute('/admin/create/')()
const AdminQuizIdIndexLazyImport = createFileRoute('/admin/$quizId/')()
const AdminQuizIdTeamsOverviewLazyImport = createFileRoute(
  '/admin/$quizId/teams-overview',
)()
const AdminQuizIdQuizControlLazyImport = createFileRoute(
  '/admin/$quizId/quiz-control',
)()
const AdminQuizIdGameOverviewLazyImport = createFileRoute(
  '/admin/$quizId/game-overview',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const QuizIdPlayLazyRoute = QuizIdPlayLazyImport.update({
  path: '/$quizId/play',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$quizId/play.lazy').then((d) => d.Route))

const QuizIdWaitingRoute = QuizIdWaitingImport.update({
  path: '/$quizId/waiting',
  getParentRoute: () => rootRoute,
} as any)

const AdminCreateIndexLazyRoute = AdminCreateIndexLazyImport.update({
  path: '/admin/create/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/create/index.lazy').then((d) => d.Route),
)

const AdminQuizIdIndexLazyRoute = AdminQuizIdIndexLazyImport.update({
  path: '/admin/$quizId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/$quizId/index.lazy').then((d) => d.Route),
)

const AdminQuizIdTeamsOverviewLazyRoute =
  AdminQuizIdTeamsOverviewLazyImport.update({
    path: '/admin/$quizId/teams-overview',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/$quizId/teams-overview.lazy').then((d) => d.Route),
  )

const AdminQuizIdQuizControlLazyRoute = AdminQuizIdQuizControlLazyImport.update(
  {
    path: '/admin/$quizId/quiz-control',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/admin/$quizId/quiz-control.lazy').then((d) => d.Route),
)

const AdminQuizIdGameOverviewLazyRoute =
  AdminQuizIdGameOverviewLazyImport.update({
    path: '/admin/$quizId/game-overview',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/$quizId/game-overview.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$quizId/waiting': {
      id: '/$quizId/waiting'
      path: '/$quizId/waiting'
      fullPath: '/$quizId/waiting'
      preLoaderRoute: typeof QuizIdWaitingImport
      parentRoute: typeof rootRoute
    }
    '/$quizId/play': {
      id: '/$quizId/play'
      path: '/$quizId/play'
      fullPath: '/$quizId/play'
      preLoaderRoute: typeof QuizIdPlayLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/$quizId/game-overview': {
      id: '/admin/$quizId/game-overview'
      path: '/admin/$quizId/game-overview'
      fullPath: '/admin/$quizId/game-overview'
      preLoaderRoute: typeof AdminQuizIdGameOverviewLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/$quizId/quiz-control': {
      id: '/admin/$quizId/quiz-control'
      path: '/admin/$quizId/quiz-control'
      fullPath: '/admin/$quizId/quiz-control'
      preLoaderRoute: typeof AdminQuizIdQuizControlLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/$quizId/teams-overview': {
      id: '/admin/$quizId/teams-overview'
      path: '/admin/$quizId/teams-overview'
      fullPath: '/admin/$quizId/teams-overview'
      preLoaderRoute: typeof AdminQuizIdTeamsOverviewLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/$quizId/': {
      id: '/admin/$quizId/'
      path: '/admin/$quizId'
      fullPath: '/admin/$quizId'
      preLoaderRoute: typeof AdminQuizIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/create/': {
      id: '/admin/create/'
      path: '/admin/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$quizId/waiting': typeof QuizIdWaitingRoute
  '/$quizId/play': typeof QuizIdPlayLazyRoute
  '/admin/$quizId/game-overview': typeof AdminQuizIdGameOverviewLazyRoute
  '/admin/$quizId/quiz-control': typeof AdminQuizIdQuizControlLazyRoute
  '/admin/$quizId/teams-overview': typeof AdminQuizIdTeamsOverviewLazyRoute
  '/admin/$quizId': typeof AdminQuizIdIndexLazyRoute
  '/admin/create': typeof AdminCreateIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$quizId/waiting': typeof QuizIdWaitingRoute
  '/$quizId/play': typeof QuizIdPlayLazyRoute
  '/admin/$quizId/game-overview': typeof AdminQuizIdGameOverviewLazyRoute
  '/admin/$quizId/quiz-control': typeof AdminQuizIdQuizControlLazyRoute
  '/admin/$quizId/teams-overview': typeof AdminQuizIdTeamsOverviewLazyRoute
  '/admin/$quizId': typeof AdminQuizIdIndexLazyRoute
  '/admin/create': typeof AdminCreateIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$quizId/waiting': typeof QuizIdWaitingRoute
  '/$quizId/play': typeof QuizIdPlayLazyRoute
  '/admin/$quizId/game-overview': typeof AdminQuizIdGameOverviewLazyRoute
  '/admin/$quizId/quiz-control': typeof AdminQuizIdQuizControlLazyRoute
  '/admin/$quizId/teams-overview': typeof AdminQuizIdTeamsOverviewLazyRoute
  '/admin/$quizId/': typeof AdminQuizIdIndexLazyRoute
  '/admin/create/': typeof AdminCreateIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$quizId/waiting'
    | '/$quizId/play'
    | '/admin/$quizId/game-overview'
    | '/admin/$quizId/quiz-control'
    | '/admin/$quizId/teams-overview'
    | '/admin/$quizId'
    | '/admin/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$quizId/waiting'
    | '/$quizId/play'
    | '/admin/$quizId/game-overview'
    | '/admin/$quizId/quiz-control'
    | '/admin/$quizId/teams-overview'
    | '/admin/$quizId'
    | '/admin/create'
  id:
    | '__root__'
    | '/'
    | '/$quizId/waiting'
    | '/$quizId/play'
    | '/admin/$quizId/game-overview'
    | '/admin/$quizId/quiz-control'
    | '/admin/$quizId/teams-overview'
    | '/admin/$quizId/'
    | '/admin/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  QuizIdWaitingRoute: typeof QuizIdWaitingRoute
  QuizIdPlayLazyRoute: typeof QuizIdPlayLazyRoute
  AdminQuizIdGameOverviewLazyRoute: typeof AdminQuizIdGameOverviewLazyRoute
  AdminQuizIdQuizControlLazyRoute: typeof AdminQuizIdQuizControlLazyRoute
  AdminQuizIdTeamsOverviewLazyRoute: typeof AdminQuizIdTeamsOverviewLazyRoute
  AdminQuizIdIndexLazyRoute: typeof AdminQuizIdIndexLazyRoute
  AdminCreateIndexLazyRoute: typeof AdminCreateIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  QuizIdWaitingRoute: QuizIdWaitingRoute,
  QuizIdPlayLazyRoute: QuizIdPlayLazyRoute,
  AdminQuizIdGameOverviewLazyRoute: AdminQuizIdGameOverviewLazyRoute,
  AdminQuizIdQuizControlLazyRoute: AdminQuizIdQuizControlLazyRoute,
  AdminQuizIdTeamsOverviewLazyRoute: AdminQuizIdTeamsOverviewLazyRoute,
  AdminQuizIdIndexLazyRoute: AdminQuizIdIndexLazyRoute,
  AdminCreateIndexLazyRoute: AdminCreateIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$quizId/waiting",
        "/$quizId/play",
        "/admin/$quizId/game-overview",
        "/admin/$quizId/quiz-control",
        "/admin/$quizId/teams-overview",
        "/admin/$quizId/",
        "/admin/create/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$quizId/waiting": {
      "filePath": "$quizId/waiting.tsx"
    },
    "/$quizId/play": {
      "filePath": "$quizId/play.lazy.tsx"
    },
    "/admin/$quizId/game-overview": {
      "filePath": "admin/$quizId/game-overview.lazy.tsx"
    },
    "/admin/$quizId/quiz-control": {
      "filePath": "admin/$quizId/quiz-control.lazy.tsx"
    },
    "/admin/$quizId/teams-overview": {
      "filePath": "admin/$quizId/teams-overview.lazy.tsx"
    },
    "/admin/$quizId/": {
      "filePath": "admin/$quizId/index.lazy.tsx"
    },
    "/admin/create/": {
      "filePath": "admin/create/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
